# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '#about'
    weight: 10
  # - name: Projects
  #   url: '#projects'
  #   weight: 30
  # - name: Talks
  #   url: '#talks'
  #   weight: 40
  - name: Publications
    url: 'https://scholar.google.com.au/citations?user=WlrfCXoAAAAJ&hl=en'
    weight: 50
  # - name: Courses
  #   url: courses/
    # weight: 60
  - name: Contact
    url: '#contact'
    weight: 70
